### ISSUE TITLE
I don't get it.

### ISSUE THREAD

**Issue by bsparks** [klei/gulp-angular-filesort#43]
If you have a module declared in each file, then the order shouldn't matter. It shouldn't try to use the modules until runtime at which everything should be all declared and ready to go.

**Comment by joakimbeng** [comment]
Yes, that's correct! But a common setup for Angular projects (at least when I wrote this plugin) was to have a file structure like this:

```javascript
// in: app/module1/index.js
angular.module('module1', ['some-dep']);

// in: app/module1/module1-ctrl.js
angular.module('module1').controller(...);

// in: app/index.js
angular.module('app', ['module1']);
```

Then the app would crash if `app/module1/module1-ctrl.js` were loaded before `app/module1/index.js`, which is what this plugin will solve.

_**side note:** I recommend everyone using something like Browserify or Webpack instead of this plugin nowadays_
